# Example automations.yaml entry
- alias: "Power state on HA start-up"
  trigger:
    platform: homeassistant
    event: start
  action:
    - service: mqtt.publish
      data:
        topic: "cmnd/sonoffs/state"
        payload: ""
    - service: mqtt.publish
      data:
        topic: cmnd/sonoffs/POWER
    - service: mqtt.publish
      data:
        topic: cmnd/sonoffs/POWER1
    - service: mqtt.publish
      data:
        topic: cmnd/sonoffs/POWER2
    - service: mqtt.publish
      data:
        topic: cmnd/sonoffs/POWER3
    - service: mqtt.publish
      data:
        topic: cmnd/sonoffs/POWER4
    - service: mqtt.publish
      data:
        topic: cmnd/sonoffs/POWER5
    - service: mqtt.publish
      data:
        topic: cmnd/sonoffs/POWER6
    - service: mqtt.publish
      data:
        topic: cmnd/sonoffs/POWER7
    - service: mqtt.publish
      data:
        topic: cmnd/sonoffs/POWER8

# Example automations.yaml entry
- alias: "Sonoff state on HA start-up"
  trigger:
    platform: homeassistant
    event: start
  action:
    - service: mqtt.publish
      data:
        topic: "cmnd/sonoffs/STATUS"
        payload: "0"
